### ISSUE TITLE
Delete Datasets not possible

### ISSUE THREAD

**Issue by michaelgoetze** [Rappsilber-Laboratory/xiView_container#66]
I can't delete any dataset. xiView asks for approval to delete, but no button is available to agree to deletion of a dataset (see image below).

The issue is browser independent (tested in Chrome, Firefox and Edge).

![image](https://user-images.githubusercontent.com/46775781/74328792-d7d55a80-4d8e-11ea-8a1a-d8d839c1ca3f.png)

**Comment by colin-combe** [comment]
hi, 
thanks - is it fixed now?
colin

**Comment by michaelgoetze** [comment]
Hi Colin, thanks for the quick reply,

It is not fixed on my end. Console says there is an uncaught TypeError at
dialog.js:70

[image: image.png]


Am Mi., 12. Feb. 2020 um 14:44 Uhr schrieb Colin <notifications@github.com>:

**Comment by colin-combe** [comment]
if you do a hard refresh of the browser (ctrfl - F5 in chrome) is it still broken?

**Comment by michaelgoetze** [comment]
I refreshed before as well, but now it works.

Thanks for the quick response!!

Am Mi., 12. Feb. 2020 um 15:49 Uhr schrieb Colin <notifications@github.com>:
